# Dotao repository has a top-level crate for the application, and lib sub-crates
[package]
name = "dotao"
version = "0.1.0"
authors = ["João Marcos Bezerra <marcospb19@hotmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/marcospb19/dotao"
description = "Dotfiles manager (WIP) inspired by Stow"
keywords = ["dotfiles"]

[dependencies]
clap = "2.33"
toml = "*"

# Our own workspace dependencies
file-tree = { path = "./file-tree" }
permissions = { path = "./permissions" }
tsml = { path = "./tsml" }

[workspace]
members = [
    ".",
    "file-tree",
    "permissions",
    "tsml",
]
