# Dotao's repository has a workspace with a top-level crate and
# other crates in divided into other folders

[package]
name = "dotao"
version = "0.1.0"
authors = ["João Marcos Bezerra <marcospb19@hotmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/marcospb19/dotao"
description = "Dotfiles manager (WIP) inspired by Stow"
keywords = ["dotfiles"]

[dependencies]
clap = "2.33"
toml = "*"

# Dependencies from us
file-structure = { path = "./file-structure" }
permissions = { path = "./permissions" }
tsml = { path = "./tsml" }

# Todo:
# When publishing a new version:
# - Update CHANGELOG.md
# - Update README.md
# - Create "crossbeam-X.Y.Z" git tag

[workspace]
members = [
    ".",
    "file-structure",
    "permissions",
    "tsml",
]
