[package]
name = "unix_file_permissions"
version = "0.1.0"
authors = ["João M. Bezerra <marcospb19@hotmail.com>"]
edition = "2018"
description = "Friendly crate for dealing with unix file permissions."
repository = "https://github.com/marcospb19/unix_file_permissions"
license = "MIT"

[dependencies]
libc = "0.2"
bitflags = "1.2.1"
