#
max_width = 120
comment_width = 100
imports_granularity = "Crate"
match_block_trailing_comma = true
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
newline_style = "Unix"
edition = "2018"
reorder_imports = true
reorder_modules = true

# Put only unstable features from here
unstable_features = true
format_strings = true
wrap_comments = true
condense_wildcard_suffixes = true
group_imports = "StdExternalCrate"
